default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: real_world_api_development

test:
  <<: *default
  database: real_world_api_test

production:
  <<: *default
  database: real_world_api_production
  username: real_world_api
  password: <%= ENV["REAL_WORLD_API_DATABASE_PASSWORD"] %>
