default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: real_world_api_development

test:
  <<: *default
  # urlに全ての情報が含まれるため、他の情報は不要
  url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  database: <%= Rails.application.credentials.config[:db_name] %>
  username: <%= Rails.application.credentials.config[:db_username] %>
  password: <%= Rails.application.credentials.config[:db_password] %>
  host: <%= Rails.application.credentials.config[:db_host] %>
