default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: real_world_api_development

test:
  <<: *default
  # urlに全ての情報が含まれるため、他の情報は不要になる
  url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  database: <%= Rails.application.credentials.production[:db][:database] %>
  username: <%= Rails.application.credentials.production[:db][:username] %>
  password: <%= Rails.application.credentials.production[:db][:password] %>
  host: <%= Rails.application.credentials.production[:db][:host] %>
